### ISSUE TITLE
有讨论群吗？手机安装xpose还是需要root权限啊

### ISSUE THREAD

**Issue by dingshuangdian** [Jinnrry/RobotHelper#1]

**Comment by Jinnrry** [comment]
没群，有问题这里讨论就好了，需要安装xposed或者edxposed框架，不需要root权限

**Comment by Jinnrry** [comment]
我代码里面有adb相关的代码，你可以改成使用adb实现点击操作，就不需要xposed。

**Comment by dingshuangdian** [comment]
感谢，我觉得写个demo展示相关关键api调用比较好。就像大多数开源框架一样。

**Comment by Jinnrry** [comment]
https://github.com/Jinnrry/RobotHelper/blob/master/Android/app/src/main/java/cn/xjiangwei/RobotHelper/GamePackage/Main.java

现在已经是demo了，昨晚更新的
