### ISSUE TITLE
关于Toast函数显示时长

### ISSUE THREAD

**Issue by chongkaechin** [Jinnrry/RobotHelper#10]
目前的Toast函数没办法更改显示时长，我自己有尝试重载了一个，但是还是没有显示更久，想请问怎么做？
附上代码：

//Toast.java

package cn.xjiangwei.RobotHelper.Tools;

import android.media.Ringtone;
import android.media.RingtoneManager;
import android.net.Uri;
import android.os.Handler;
import android.os.Looper;
import android.os.Vibrator;

import cn.xjiangwei.RobotHelper.MainApplication;

import static android.content.Context.VIBRATOR_SERVICE;

public class Toast {

    /**
     * Toast提示
     * @param msg
     */
    public static void show(final String msg) {
        Handler handler = new Handler(Looper.getMainLooper());
        handler.post(new Runnable() {
            public void run() {
                android.widget.Toast.makeText(MainApplication.getInstance(), msg, android.widget.Toast.LENGTH_LONG).show();
            }
        });
    }

    /**
     * Toast提示
     * @param msg
     * @param duration
     */
    public static void show(final String msg,int duration) {
        Handler handler = new Handler(Looper.getMainLooper());
        handler.post(new Runnable() {
            public void run() {
                android.widget.Toast.makeText(MainApplication.getInstance(), msg, duration).show();
            }
        });
    }

    /**
     * 声音提示
     */
    public static void notice() {
        Uri notification = RingtoneManager.getDefaultUri(RingtoneManager.TYPE_NOTIFICATION);
        Ringtone r = RingtoneManager.getRingtone(MainApplication.getInstance(), notification);
        r.play();
        Vibrator vibrator = (Vibrator) MainApplication.getInstance().getSystemService(VIBRATOR_SERVICE);
        vibrator.vibrate(1000);
    }
}

//Main.java

package cn.xjiangwei.RobotHelper.GamePackage;

import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.os.Environment;

import org.opencv.android.Utils;
import org.opencv.core.Core;
import org.opencv.core.CvType;
import org.opencv.core.Mat;
import org.opencv.imgproc.Imgproc;

import java.io.IOException;
import java.io.InputStream;

import cn.xjiangwei.RobotHelper.MainApplication;
import cn.xjiangwei.RobotHelper.Tools.Image;
import cn.xjiangwei.RobotHelper.Tools.MLog;
import cn.xjiangwei.RobotHelper.Tools.Point;
import cn.xjiangwei.RobotHelper.Tools.Robot;
import cn.xjiangwei.RobotHelper.Tools.ScreenCaptureUtil;
import cn.xjiangwei.RobotHelper.Tools.TessactOcr;
import cn.xjiangwei.RobotHelper.Tools.Toast;

import static android.os.SystemClock.sleep;

public class Main {
    private static final String SD_PATH = Environment.getExternalStorageDirectory().getPath();

    /**
     * 在这个函数里面写你的业务逻辑
     */
    public void start() {
        sleep(5000); //点击开始后等待5秒后再执行，因为状态栏收起有动画时间，建议保留这行代码

        /****************************  模板匹配demo  *******************************/
        InputStream is = null;
        try {
            is = MainApplication.getInstance().getAssets().open("Chrome_Icon_bmp.bmp");
        } catch (IOException e) {
            e.printStackTrace();
        }

        Bitmap bitmap = BitmapFactory.decodeStream(is);

        Toast.show(bitmap.toString());

        //在当前屏幕中查找模板图片
        Point point = Image.matchTemplate(ScreenCaptureUtil.getScreenCap(), bitmap, 0.7);
        MLog.info("找到模板", point.toString());
        Toast.show(point.toString());

        // 点击找到的这个图
        Robot.tap(point);
        Toast.show("tap!");

        /**************************** 文字识别demo  **********************************/
        try {
            //识别素材文件中的ocrTest.png图片中的文字
            is = MainApplication.getInstance().getAssets().open("ocrTest.png");
        } catch (IOException e) {
            e.printStackTrace();
        }
        bitmap = BitmapFactory.decodeStream(is);
        String res = TessactOcr.img2string(bitmap, "chi_sim", "", "");
        MLog.info("文字识别结果：" + res);

        Toast.show(res,10000);

        /*****************************  特征点找图  ************************************/
        //当前屏幕中查找chrome图标（特征点是3120X1440分辨率手机制作）
        point = Image.findPointByMulColor(ScreenCaptureUtil.getScreenCap(), "434FD7,65|0|414DDB,90|55|46CDFF,5|86|5FA119");
        //点击chrome图标
        Robot.tap(point);

        /***** 提示  *****/
        Toast.show("运行结束！");
        //声音提示
        Toast.notice();

    }

}

**Comment by Jinnrry** [comment]
android 4.0以后Toast不支持自定义时间了，时间只有长（3.5s）、短(2s)这两种，我工具类里面用的2s的时间
