### ISSUE TITLE
切换应用的办法

### ISSUE THREAD

**Issue by chongkaechin** [Jinnrry/RobotHelper#22]
目前没有找到可以从一个应用切换到另一个应用的方法，我的场景是这样的，在一个游戏里执行一些动作后切换到Gmail应用读取验证码，然后回到游戏来输入得到的验证码。

我觉得似乎可以取得应用包名然后用instrumentation类来做，不过具体怎么写没有想法。想请教一些作者有没有什么思路。

**Comment by chongkaechin** [comment]
暂时用其他方法解决了。
我写了一个回到首页的功能，这样就可以应付我的需求了。

在Robot.java添加这些代码


 private static Instrumentation rInst = new Instrumentation();

    /**** Home Button ****/
    public static void home(){
        rInst.sendKeyDownUpSync(KeyEvent.KEYCODE_HOME);
    }

**Comment by Jinnrry** [comment]
1.切换应用 https://juejin.im/entry/6844903493803704334

2.我觉得你这个需求完全不需要打开gmail，你直接用pop或者imap协议读邮件内容不就行了，这样比你打开gmail读内容健壮多了

**Comment by chongkaechin** [comment]
关于作者你提的第二点可以有更详细的说明吗，还是有建议的参考资料吗，我对你说的东西不是很了解，谢谢

**Comment by Jinnrry** [comment]
https://www.liaoxuefeng.com/wiki/1252599548343744/1319099948859426
