### ISSUE TITLE
启动/关闭某个程序

### ISSUE THREAD

**Issue by wnight9527** [Jinnrry/RobotHelper#24]
有些游戏优化不好，运行久了就变卡了。

**Comment by Jinnrry** [comment]
是游戏导致变卡了还是我这个程序导致变卡了？如果是游戏导致的，那我也没办法呀。

**Comment by wnight9527** [comment]
就是我用无障碍模式的，想了解怎么能关闭启动游戏程序，国外的手游，运行久了就卡偏
