### ISSUE TITLE
截取部分画面，会出现坐标轴偏移的问题

### ISSUE THREAD

**Issue by wnight9527** [Jinnrry/RobotHelper#25]
雷电模拟器，无障碍模式，截取屏幕，720*1280 320dpi。
截取0，0，720，1280。会包含两边的黑框。导致不是实际想截取的画面。。。
是要每个机型适配，还是有匹配的方法的？大佬

**Comment by wnight9527** [comment]
全屏接下来 是两边有黑屏区域的。有什么办法能和tap点击匹配吗。。。。点击是按左上角坐标轴横720纵，1280。截屏的就成了横1280纵720了。导致区域截图匹配并点击就有点麻烦。。不会是要一个个机型适配吧

**Comment by Jinnrry** [comment]
我有空看看先，以前没遇到过这种情况

**Comment by Jinnrry** [comment]
你是在竖屏的情况下启动应用，然后在竖屏情况下截取的图像？之前还真没考虑这种情况，一般游戏都是横屏的，截图都是直接按横屏处理的

**Comment by wnight9527** [comment]
hhh，挂机类的刷刷刷的手游。。确实是竖屏。。。所以会出点问题。麻烦大佬兼容下

**Comment by wnight9527** [comment]
希望截屏有参数选择按竖屏截取，获取竖屏模式的坐标。不然点击按竖屏，截图按横屏，兼容会疯的

**Comment by Jinnrry** [comment]
https://github.com/Jinnrry/RobotHelper/blob/385f2c38def90efeda13fabc71c32c358e7ca41f/Android/app/src/main/java/cn/xjiangwei/RobotHelper/Tools/ScreenCaptureUtilByMediaPro.java#L38

你可以先在这里调换横纵坐标顺序，后面有空可以优化一下这里的代码逻辑

**Comment by Jinnrry** [comment]
#28 

截图函数添加了自动判断屏幕方向
