### ISSUE TITLE
基于web接口开发的实际使用方法

### ISSUE THREAD

**Issue by chongkaechin** [Jinnrry/RobotHelper#27]
在网上找过了一遍但是还是不太理解而且也没有相关基础，可以麻烦作者写一段相关代码吗，还有代码放在哪里之类的。

**Comment by Jinnrry** [comment]
是用来做集群使用的。比如你需要开发一个爬虫集群，使用100台手机当worker，这个时候就需要一个master服务器去管理每个worker的工作，web api的初衷就是用来和master通讯的。使用webapi实现master去调度所有的worker

至于放哪里，怎么写，使用什么架构，这是你master服务器的业务逻辑。

**Comment by Jinnrry** [comment]
这种业务逻辑网上肯定没有现成的介绍，是这个项目独有的设计

**Comment by chongkaechin** [comment]
我会想要试试看这个方法是因为有看到作者有写可以获得页面上的dom。虽然我不是很确定这个是什么，但是感觉dom有点像当下屏幕上的各种元素。

因为如果每次点击前都使用matchtemplate感觉很耗资源，所以想说有没有可以获得屏幕上物件的方法。我感觉accessibility,也就是无障碍服务提权好像可以做到。不知道是我的这样吗。

希望作者能够表达一下看法或是提出建议，谢谢。

**Comment by Jinnrry** [comment]
是的，获取dom的底层实现就是accessibility，我把accessibility的结果转成json结构返回了而已

**Comment by chongkaechin** [comment]
那实际使用上是使用哪几个函数呢？函数参数的定义又是什么，可以麻烦作者稍微提一下吗？谢谢。

**Comment by Jinnrry** [comment]
web接口，这个是接口，是web api 接口，使用http协议调用，并不是java函数调用[web api](https://github.com/Jinnrry/RobotHelper/wiki/%E5%9F%BA%E4%BA%8EWEB%E6%8E%A5%E5%8F%A3%E7%9A%84%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97) 这里详细介绍了每个api调用方法

[实现位置](https://github.com/Jinnrry/RobotHelper/blob/master/Android/app/src/main/java/cn/xjiangwei/RobotHelper/Accessibility/HttpServer.java)这里是底层实现
