### ISSUE TITLE
能否考虑增加支持数字识别？

### ISSUE THREAD

**Issue by wnight9527** [Jinnrry/RobotHelper#30]
目前内置的文字识别方法对数字的准确度很低。游戏里很多地方要识别数字。
按键精灵有那种定义10个数字点阵的方式，准确度还挺高的，大大能否考虑下。

**Comment by Jinnrry** [comment]
目前支持的，你可以调文字识别的时候把白名单设置成0123456789

**Comment by wnight9527** [comment]
> 目前支持的，你可以调文字识别的时候把白名单设置成0123456789

试过了，发现识别准确率不行

**Comment by wnight9527** [comment]
游戏里一个是数字字体和常规字体不一样，一个是背景花里胡哨。所以导致识别准确率不太行。按键精灵那个是有个专门的算法提供数字识别的，估计费了挺大劲的，不知道怎么实现的。

**Comment by Jinnrry** [comment]
1.你可以改成英语模型，不要用中文模型识别数字
2.你需要去背景后再提交识别
3.模式都是印刷字体，你可以自己训练模型，训练方法搜索“tesseract 训练”

更多调优方法你可以搜搜 “tesseract 验证码识别”

**Comment by wnight9527** [comment]
了解，我试试看
