### ISSUE TITLE
能告诉我你的安卓环境吗

### ISSUE THREAD

**Issue by Valkdandy** [Jinnrry/RobotHelper#31]
我在android studio 4.11上 使用雷电模拟器64 运行截图失败了.我发现你的源码使用 gradle5.11.
    能说说你正常运行的android studio版本和使用的什么模拟器吗  .安卓模拟器推荐用什么版本啊? 现在是安卓11.

**Comment by Jinnrry** [comment]
报错是啥，我也是用的雷电，安卓11我没测试过，我之前是安卓7

**Comment by Valkdandy** [comment]
我使用了另一个截图代码,解决了问题.谢谢.

能不能问一下你有什么好的办法获得用户后台点击坐标吗.root 也可以. 

Runtime.getRuntime().exec(new String[]{"/system/bin/su","-c", "getevent"});  这个我一直无法成功获得数据流 InputStream

**Comment by Jinnrry** [comment]
`cat /dev/input/event2`

你直接读取input/event文件里面的内容就行了，这个是linux下面输入设备的资源文件。你只需要找到你需要监听第几个输入设备，然后读取就行了。

[sendevent](https://android.googlesource.com/platform/system/core/+/android-5.0.2_r3/toolbox/sendevent.c)

[getevent](https://android.googlesource.com/platform/system/core/+/android-5.0.2_r3/toolbox/getevent.c)

这两个是安卓读取和输入event的实现源码，你看下这个就知道了

**Comment by Valkdandy** [comment]
谢谢你,我去试试.   我仔细看了你的自制按键精灵所有文章,真是佩服死了.我也是想自制一款按键精灵.也花了不少时间啦.要是早看见你的项目,就好了.

**Comment by Valkdandy** [comment]
我当时以为按键精灵不就是点击截图找色嘛,结果一头栽进去了,谷歌正好严格限制这些, cmd命令也是费了牛劲,说起来真惨哈...按键精灵还是有点技术含量,一般人真是太难了,只能乖乖用按键了.可惜用它不但花钱广告,很多功能实现不了.还有很多莫名的程序bug,经常死得莫名其妙
