### ISSUE TITLE
我看到作者你在博客里提到通过lua脚本控制程序，是没放进来吗

### ISSUE THREAD

**Issue by wnight9527** [Jinnrry/RobotHelper#33]

**Comment by wnight9527** [comment]
java调试起来确实有点麻烦

**Comment by Jinnrry** [comment]
是的，我第一版是引入了lua脚本的，但是后面仔细思考了下，java对业务的抽象能力，工程化开发能力，完全碾压lua，在项目里面引入lua写业务逻辑完全就是本末倒置。按键精灵引入vb，触动精灵引入lua，autojs引入js，他们都是为了降低入门难度，让很多不懂开发的人也能写脚本。但是我这个项目不是为了让普通人能够开发，我是希望能够用上更多安卓原生的能力，因此完全没必要实用lua

另外，java作为工业界这么多年的常青树，而且在android这么成熟的领域，调试起来肯定比lua方便多了。你可以看看as的断点调试方法，java有很多不足，但是调试不方便绝对不是他的弱项

**Comment by wnight9527** [comment]
> 是的，我第一版是引入了lua脚本的，但是后面仔细思考了下，java对业务的抽象能力，工程化开发能力，完全碾压lua，在项目里面引入lua写业务逻辑完全就是本末倒置。按键精灵引入vb，触动精灵引入lua，autojs引入js，他们都是为了降低入门难度，让很多不懂开发的人也能写脚本。但是我这个项目不是为了让普通人能够开发，我是希望能够用上更多安卓原生的能力，因此完全没必要实用lua
> 
> 另外，java作为工业界这么多年的常青树，而且在android这么成熟的领域，调试起来肯定比lua方便多了。你可以看看as的断点调试方法，java有很多不足，但是调试不方便绝对不是他的弱项

另一方面也是为了效率吧，如果不是按键精灵容易出问题。。我也不想用原生，按键精灵函数很全😂😂

**Comment by wnight9527** [comment]
> > 是的，我第一版是引入了lua脚本的，但是后面仔细思考了下，java对业务的抽象能力，工程化开发能力，完全碾压lua，在项目里面引入lua写业务逻辑完全就是本末倒置。按键精灵引入vb，触动精灵引入lua，autojs引入js，他们都是为了降低入门难度，让很多不懂开发的人也能写脚本。但是我这个项目不是为了让普通人能够开发，我是希望能够用上更多安卓原生的能力，因此完全没必要实用lua
> > 另外，java作为工业界这么多年的常青树，而且在android这么成熟的领域，调试起来肯定比lua方便多了。你可以看看as的断点调试方法，java有很多不足，但是调试不方便绝对不是他的弱项
> 
> 另一方面也是为了效率吧，如果不是按键精灵容易出问题。。我也不想用原生，按键精灵函数很全😂😂

还有按键精灵的编译器太垃圾了。。

**Comment by Jinnrry** [comment]
这种业务场景来说性能不是啥问题，现在的硬件都不差这点性能问题。按键精灵毕竟是商业软件，有专门的团队维护，函数不全也不至于成为这个领域的头牌。他那些函数是他的优势，但是也限制了他的发展空间，他那些函数始太死了，扩展性几乎为0。

按键精灵虽然也提供了lua脚本的插件扩展，但是功能上来说也非常局限，很多东西几乎没法扩展。这也是我自己搞这个项目的原因

**Comment by Jinnrry** [comment]
其实从架构上来说，按键精灵里面所有能实现的功能，这个项目里面都能实现，他那些函数没啥算法难度的。最多就费点时间而已。

我以前有个脚本，按键精灵的vb代码写了两万多行了，最后都用这个框架重写了，中间没有遇到任何不能解决的。而且性能，稳定性远超原来的
