### ISSUE TITLE
像基础的返回主页，返回按钮之类的是不是可以加进来

### ISSUE THREAD

**Issue by wnight9527** [Jinnrry/RobotHelper#34]
增加几个函数
类似这种
Accessibility.getInstance().performGlobalAction(AccessibilityService.GLOBAL_ACTION_BACK);

**Comment by wnight9527** [comment]
E/AndroidRuntime: FATAL EXCEPTION: Thread-2
    Process: cn.xjiangwei.RobotHelper, PID: 19249
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean cn.xjiangwei.RobotHelper.Service.Accessibility.performGlobalAction(int)' on a null object reference
在新项目里测试没问题，加入robothelper里就报这个错。

**Comment by wnight9527** [comment]
搞定了。。。一条条看源码加进去了。。。

**Comment by Jinnrry** [comment]
有空的话，返回按钮可以提个mg，我合到主分支。其他人可能也会用到

**Comment by wnight9527** [comment]
我看下怎么提交，还没提交过 = =

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: 木木的木头<mailto:notifications@github.com>
发送时间: 2020年12月20日 21:55
收件人: Jinnrry/RobotHelper<mailto:RobotHelper@noreply.github.com>
抄送: white<mailto:wnight9527@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [Jinnrry/RobotHelper] 像基础的返回主页，返回按钮之类的是不是可以加进来 (#34)


有空的话，返回按钮可以提个mg，我合到主分支。其他人可能也会用到

―

**Comment by wnight9527** [comment]
> 有空的话，返回按钮可以提个mg，我合到主分支。其他人可能也会用到

AccessibilityInput.class
    public  void getBack() {

         Accessibility.getInstance().performGlobalAction(AccessibilityService.GLOBAL_ACTION_BACK);

    }
就是这个方法。我这git提交会出错也不知道怎么回事。作者你加进去把

**Comment by wnight9527** [comment]
AccessibilityInput.class
public void getHome() {

     Accessibility.getInstance().performGlobalAction(AccessibilityService.GLOBAL_ACTION_HOME);

}

**Comment by wnight9527** [comment]
只实现了无障碍的，root和xposed都是个空
