### ISSUE TITLE
图片模板匹配

### ISSUE THREAD

**Issue by louis2610** [Jinnrry/RobotHelper#39]
图片模板匹配成功概率有点低，还会造成crash，有什么好的配置阈值吗？

**Comment by Jinnrry** [comment]
模板匹配是用的opencv里面的算法，你可以看看opencv的模板匹配相关参数。

**Comment by louis2610** [comment]
你好，我遇到一个问题，我在玩游戏时，用系统的截屏函数截出张图，用来测试，脚本也通过多色取点函数找到了某个点，但是当再次进入到手机，遇到同一张图片反而找不出来，不知道你有遇到过吗？难道系统的截屏，跟游戏运行时分辨率不一致吗？

**Comment by Jinnrry** [comment]
你把程序截图函数截到的图片保存下来看看，可能是截图方向错了

**Comment by louis2610** [comment]
都是横屏的

**Comment by Jinnrry** [comment]
你拿程序得到的截屏和系统截屏对比下呢

**Comment by louis2610** [comment]
我看了，程序截屏和系统截屏是一样的。具体操作如下：
我在游戏里直接跑脚本是能正常识别出某个点的（游戏中），退出游戏后，我单独对这张图片（不管是系统截屏，还是程序里的函数截屏，只要是退出了游戏，我对这张图全屏展示的时候）进行找点就失败（跟游戏中的截屏找点函数一致，没有任何改动）；

**Comment by Jinnrry** [comment]
全屏展示和游戏截图不一定一样呀，可能会出现色差。

你如果是测试截图的话，你需要在程序里面打开相册里面的图片，然后执行找点程序

**Comment by louis2610** [comment]
我说的全屏其实就是原图大小。
我的疑惑点是，你的抓图工具和系统截屏有什么区别，游戏中时用你的工具抓，和用系统截屏没有不一样吧。
