### ISSUE TITLE
请问一下一些脚本的功能

### ISSUE THREAD

**Issue by ff2222** [Jinnrry/RobotHelper#42]
1 请问这个软件是否有录制脚本的功能 就是读取玩家的触摸坐标。是用什么实现的 Instrumentation  adb 还是辅助功能  请提示一下 我再去你的代码相应部分里面仔细寻找。

2 这个软件生成的apk 很大 如果多台机器安装更新一下会很吃力 有精简的版本吗。

3 让游戏无法检测是模拟器还是手机 这种可能性存在吗 业界实现了吗。

    最后感谢一下作者 竟然能做出如此优秀的软件 一个人就把按键精灵一个大公司给比下去了 哈哈。还是免费的。

**Comment by Jinnrry** [comment]
1.没有录制功能
2.你可以把文字识别和opencv模块去掉，apk就只有3M左右了
3.理论上不可能实现，电脑模拟器一般都是x86cpu，手机一般是arm，理论上可以使用cpu指令集检测，另外，模拟器和手机有大量的环境变量不一致
