### ISSUE TITLE
二值化找图

### ISSUE THREAD

**Issue by louis2610** [Jinnrry/RobotHelper#45]
请问支持二值化找图吗

**Comment by Jinnrry** [comment]
什么叫二值化找图？

**Comment by louis2610** [comment]
> 什么叫二值化找图？
类似这种
https://helpdoc.touchsprite.com/dev_docs/18/5.html?q=

**Comment by Jinnrry** [comment]
看了一下，目前没有现成的。但是要实现很简单。目前框架里面已经有opencv了，使用opencv将原图和模板图二值化，然后用模板匹配函数就行了。

相关资料： https://my.oschina.net/u/4315935/blog/4187765

ps: 目前[多色找点函数](https://github.com/Jinnrry/RobotHelper/blob/a29302d5e4f56f3c99b77c16202c91fde48571c6/Android/app/src/main/java/cn/xjiangwei/RobotHelper/Tools/Image.java#L161)带了一个offset参数，这个参数能够处理色差问题。没必要非把图片做二值化。我觉得无论从效率还是准确性上面，使用点找目标都更好

**Comment by louis2610** [comment]
> 看了一下，目前没有现成的。但是要实现很简单。目前框架里面已经有opencv了，使用opencv将原图和模板图二值化，然后用模板匹配函数就行了。
> 
> 相关资料： https://my.oschina.net/u/4315935/blog/4187765
> 
> ps: 目前[多色找点函数](https://github.com/Jinnrry/RobotHelper/blob/a29302d5e4f56f3c99b77c16202c91fde48571c6/Android/app/src/main/java/cn/xjiangwei/RobotHelper/Tools/Image.java#L161)带了一个offset参数，这个参数能够处理色差问题。没必要非把图片做二值化。我觉得无论从效率还是准确性上面，使用点找目标都更好

二值化后的黑白图，也能通过调用模板匹配函数跟彩色的原图匹配？

**Comment by Jinnrry** [comment]
肯定不可以呀，我的意思是模板图片和截图都同时做二值化

**Comment by louis2610** [comment]
> 肯定不可以呀，我的意思是模板图片和截图都同时做二值化

大神，一般动图如何匹配？

**Comment by Jinnrry** [comment]
动图匹配是什么场景？截成每一帧，然后单独匹配行吗

**Comment by louis2610** [comment]
> 动图匹配是什么场景？截成每一帧，然后单独匹配行吗

比如识别甚至装备，背景是闪烁的

**Comment by Jinnrry** [comment]
你看下多色找点函数，对应按键精灵的FindMutiColorEx 函数，这个函数就是专门解决这种问题的

**Comment by louis2610** [comment]
> 你看下多色找点函数，对应按键精灵的FindMutiColorEx 函数，这个函数就是专门解决这种问题的

静态图是可以多点找色，但是动图的话不太合适

**Comment by Jinnrry** [comment]
先找第一帧，发现第一帧后继续检查后续桢是否匹配可以吗

**Comment by louis2610** [comment]
> 先找第一帧，发现第一帧后继续检查后续桢是否匹配可以吗

这也是一种方法，但不是最合理的，一般是做点阵
