### ISSUE TITLE
这个框架还可以正常运行吗？

### ISSUE THREAD

**Issue by cpg868** [Jinnrry/RobotHelper#48]
我之前用这个框架写的脚本都是可以正常运行的，现在都不行了。重新编译也不行，界面正常打开，点击开始脚本没有任何反应，编译运行也没有报错。但没有执行Start方法，大家有没有遇到类似的情况？

**Comment by Jinnrry** [comment]
是最新版本的吗？你打断点跟一下运行过程，看下在哪退出的呢
