### ISSUE TITLE
getScreenCapHorizontal 中的  bitmapCacheVertical.isRecycled() 错误

### ISSUE THREAD

**Issue by HuRuWo** [Jinnrry/RobotHelper#55]
bitmapCacheVertical.isRecycled() 应该改为
bitmapCacheHorizontal.isRecycled()

这个库相当不错

**Comment by Jinnrry** [comment]
给个代码位置？没找到这行代码呢

**Comment by HuRuWo** [comment]
ScreenCaptureUtilByMediaPro 的 getScreenCapHorizontal

**Comment by Jinnrry** [comment]
已经改了，感谢指出
