### ISSUE TITLE
input往输入框输入文字留的有接口，有计划实现吗

### ISSUE THREAD

**Issue by bigursa** [Jinnrry/RobotHelper#57]
之前的文字识别有点不准，我把文字识别的换成调用PaddleOCR了，识别很好，现在xp框架版挺好的，可惜输入功能没实现，想问一下XP框架版有办法实现吗，有计划后边实现输入功能吗

**Comment by Jinnrry** [comment]
最简单的办法就是直接把文本放到剪切板去，然后在需要输入的知道执行粘贴。

最优的方法是自定义输入法，然后通过自定义输入法输入。

目前暂时没有实现计划。其他人有实现的话欢迎pr

**Comment by bigursa** [comment]
嗯 粘贴这种是比较简单  用XP框架弄粘贴也是模拟手动操作 长按然后出来粘贴了点吗 还是说有办法像windows一样直接调用粘贴方法就过去了呢 之前写过电脑上的超级剪切板手机上的不太懂

**Comment by Jinnrry** [comment]
你直接模拟按键Ctrl+v。Android系统也是支持键盘的

**Comment by Jinnrry** [comment]
不过如果你是开发游戏脚本的话最好别这样干，特征太明显，容易被发现

**Comment by bigursa** [comment]
嗯 游戏的检测还是挺严格的估计这样搞是不太好 多谢提醒

**Comment by Jinnrry** [comment]
#59

**Comment by Jinnrry** [comment]
https://github.com/Jinnrry/RobotHelper/pull/59  文本输入功能已经实现了
