### ISSUE TITLE
前来学习~ 手机未root的情况下也能点击吗

### ISSUE THREAD

**Issue by jeryZH** [Jinnrry/RobotHelper#6]
貌似app里调用adb命令是需要root权限的

**Comment by Jinnrry** [comment]
对，未root的情况不能在应用里面使用adb命令点击，

但是我这个项目是用的xposed框架实现的点击，必须得有xposed框架，和root没有什么关系

**Comment by Jinnrry** [comment]
😃😃新版本，支持无障碍了，可以不需要root或者xposed权限了
