### ISSUE TITLE
大佬的网站打不开了

### ISSUE THREAD

**Issue by TryLoveCatch** [Jinnrry/RobotHelper#61]
www.xjiangwei.cn打不开了

**Comment by Jinnrry** [comment]
被墙了，需要挂梯子

**Comment by TryLoveCatch** [comment]
> 被墙了，需要挂梯子

大佬回复真快~
明白了，我把网站增加到规则里

**Comment by Jinnrry** [comment]
xjiangwei.cn 这个域名是重定向到 jinnrry.com这个域名的，这2个域名都得加到规则里。后续会废弃掉cn的域名

**Comment by TryLoveCatch** [comment]
收到

> xjiangwei.cn 这个域名是重定向到 jinnrry.com这个域名的，这2个域名都得加到规则里。后续会废弃掉cn的域名
