### ISSUE TITLE
哪位兄弟给个简单的安装流程？

### ISSUE THREAD

**Issue by kymowang** [Jinnrry/RobotHelper#64]
不会安卓开发，给简单的列一下怎么安装或者需要什么环境，多谢

**Comment by Jinnrry** [comment]
1、下载并安装Android studio https://developer.android.com/codelabs/basic-android-kotlin-compose-install-android-studio?hl=zh-cn

2、克隆该项目

3、打开android studio，选择打开已有项目，文件夹选择这个项目的`Android` 文件夹

4、等待as自动下载依赖（自行配置代理）

5、as里面打开[Main.java](https://github.com/Jinnrry/RobotHelper/blob/master/Android/app/src/main/java/cn/xjiangwei/RobotHelper/GamePackage/Main.java) 开始编写你的业务代码
