### ISSUE TITLE
我有个小问题

### ISSUE THREAD

**Issue by iblue007** [Jinnrry/RobotHelper#7]
这个要怎么使用呀，能不能来个说明
我跑起来 提示我xp框架加载失败
里面有个OcrServer 和python要怎么使用？
求大佬解惑

**Comment by Jinnrry** [comment]
xp框架你只是安装了app吧？需要自己卡刷xposed模块的。如果你手机root过了，你可以直接安装xposed  app里面点击安装就行。

网上找了下，这个安装教程写得不错：
https://www.jianshu.com/p/2ccbfa96211c

**Comment by Jinnrry** [comment]
OCRserver已经废弃了，可以不管。python那个是开发工具，你不会用的话可以自己用ps或者Windows的绘画板找点，找色，裁剪图片

**Comment by Jinnrry** [comment]
@iblue007 xposed在安卓高版本依赖Magisk，安装比较复杂

**Comment by iblue007** [comment]
> https://www.jianshu.com/p/2ccbfa96211c

这个要root才行吗

> @iblue007 xposed在安卓高版本依赖Magisk，安装比较复杂

作者考虑出一个教程吗 ，不然感觉大家都不会用，有的功能需要

**Comment by iblue007** [comment]
> > https://www.jianshu.com/p/2ccbfa96211c
> 
> 这个要root才行吗
> 
> > @iblue007 xposed在安卓高版本依赖Magisk，安装比较复杂
> 
> 作者考虑出一个教程吗 ，不然感觉大家都不会用，有的功能需要

需要root权限吗

**Comment by Jinnrry** [comment]
@iblue007  我这个项目只是依赖xposed而已，xposed相关的使用教程还是建议看xda之类的论坛吧。具体安装和使用教程的话可以看看这几个。我这个项目兼容原版xposed和edxposed的，这2种都可以

https://www.xda-developers.com/xposed-framework-hub/

http://edxp.meowcat.org/

https://repo.xposed.info/module/de.robv.android.xposed.installer
